# H2
spring:
  datasource:
    url: jdbc:h2:~/ctdb;DB_CLOSE_ON_EXIT=FALSE
  jpa:
    hibernate:
      ddl-auto: update
  h2:
    console:
      enabled: true
      path: /h2

cryptocompare:
  url: https://min-api.cryptocompare.com
  topSymbolsByVolumePath: /data/top/totalvol?tsym=USD&limit=100
  symbolSnapshotPath: /data/top/exchanges/full?tsym=USD&limit=100&fsym=
  exchangeDataStaleAfter: 12 # hours
  exchangeWhitelist:
    - Bitfinex
    - Coinbase
    - Bitstamp
    - Kraken
    - Gemini
    - HitBTC
    - BitTrex
    - itBit
    - TrustDEX
    - Poloniex
    - Yobit
    - BitBay
    - WavesDEX
    - Kucoin